services:
  mongo:
    image: mongo:4.0.28-xenial
    # image: mongo:5.0.6-focal
    container_name: example-container-mmongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: test
    networks:
      - default
    ports:
      - 27017:27017
    volumes:
      - .docker/mongo/init:/docker-entrypoint-initdb.d:ro
      # - .docker/mongo/conf:/etc/mongo/:ro

networks:
  default:
    name: example-network-default
